### ISSUE TITLE
Peer-to-peer: code review

### ISSUE THREAD

**Issue by Leboroz** [zhadier/Leaderboard#4]
Hello Zeeshan 👋 

Your code looks amazing, it really shows how much effort you put into this. 👍 I love the fact that you added unique features like easter eggs and theme-styled pictures.

<img src="https://media3.giphy.com/media/QXPmPdudTz4So2P4OQ/giphy.gif"/>

## highlight: 💯 
 - the code looks clean and organized.

## Things to improve:
- The eastern eggs are not very intuitive. You should label them so people don't think is a bad feature.
- the scroll bar is difficult to see. Maybe you could play with the opacity.
- You should add environment variables to hide your id. People could hack your scores 😨 .

**Comment by zhadier** [comment]
# Hey @Leboroz  :high_brightness: 
#### Thank you so much for the kind words and the amazing recommendations:last_quarter_moon_with_face:, it means a lot coming from an amazing developer like you and I'll be adding these features soon for sure :smiley: :rice_cracker: 
<img src="https://media1.giphy.com/media/fsW2XJQYnmnaKV55eg/giphy.gif"/>
